import { Outfit } from 'next/font/google';
import './globals.css';
import Header from './_components/Header';
import Footer from './_components/Footer';

const outfit = Outfit({
  subsets: ['latin'],
  variable: '--font-montserrat', 
  display: 'swap',
});


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${outfit.className} antialiased`}>
        <div className='md: px-5 max-w-6xl mx-auto'>
          <Header />
          {children}
        </div>
          <Footer />
      </body>
    </html>
  );
}
